# -*- coding: utf-8 -*-
"""task03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1THmGt9siL3osdGMiIvuC41f3O2Qe5fDq
"""

flag= 0
def merge(a,b) :
  global flag
  i=0
  j=0
  em_list=[]
  
  while (i<len(a) and j<len(b)) :
    if(a[i]<b[j]) :
      em_list.append(a[i])
      i=i+1
    
    else :
      em_list.append(b[j])
      j=j+1
      flag= flag +(len(a)-i)
  
  while(i<len(a)) :
      em_list.append(a[i])
      i=i+1
  
  while(j<len(b)) :
      em_list.append(b[j])
      j=j+1
  return em_list

def merge_sort(arr) :
  if(len(arr)== 1) :
    return arr
  
  mid=(len(arr))// 2
  a=merge_sort(arr[: mid] )
  b=merge_sort(arr[mid:] )
  
  return merge(a,b)       
#---------------------------------------
inp_file=open('input3.txt',"r")
out_file=open('output3.txt',"w")
temp= int(inp_file.readline() )
array_1 = []

for a in inp_file.readline().split() :
  array_1.append (int(a))
sorted_arr=merge_sort(array_1)
sorted = ""

for a in sorted_arr :
  sorted= sorted+str(a)+ " "


out_file.write(str(flag))
#--------------
inp_file.close()
out_file.close()