# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k-GnrRF-rVRy14wCdg47HTUBrPpzeQ7E
"""

#task 02
def max_num(array) :
  temp= len(array)
  if temp == 1 :
    return array [0]
  
  else:
    middle = temp// 2
    
    l_max =max_num(array[: middle])
    r_max =max_num(array[middle :])
    return max(l_max, r_max)

#----------------------------
inp_file= open('input2.txt',"r")
out_file= open('output2.txt',"w")
temp = int(inp_file.readline() )
array = list (map (int,inp_file.readline().split() ))

final= max_num(array)
out_file.write(str(final))
#--------------
inp_file.close()
out_file.close()