# -*- coding: utf-8 -*-
"""task1_b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aTyWq_TWNe8-w4oCWqF3NQcn4gIuary1
"""

inp_file=open('input1_b.txt',"r")
out_file=open('output1_b.txt',"w")
empty_lst=[]
num_list=[]
read_line=inp_file.readline()
t_line=read_line.split()


for a in range(2,len(t_line)) :
  empty_lst.append (int(t_line[a]))

temp=inp_file.readlines()
for b in range(len(temp)) :
  store=temp[b]
  
  for x in store :
    if x.isdigit() :
      num_list.append(int(x))
#-----------------------------------------
def partition_f(array,first,last) :
  save=array[last]
  x=first-1
  
  for b in range(first,last) :
    
    if array[b]<save :
      x=x+1
      array[x],array[b]= array[b],array[x]
  array[x+1],array[last]= array[last],array[x+1]
  final_val=x+1
  return final_val
#------------------------------------
def find_K(array,first,last,k) :
  
  if k<= last-first+1:
    temp_2=partition_f(array,first,last)
    
    if temp_2-first== k-1 :
      return array[temp_2]
    
    if temp_2-first>k-1 :
      return find_K(array,first,temp_2-1 ,k)
    
    return find_K(array,temp_2+1,last, k-temp_2+first-1)
#---------------------------------------------        
for y in num_list:
  final_val=find_K(empty_lst, 0,len(empty_lst)-1, y)
  
  print(final_val,file=out_file)
inp_file.close()
out_file.close()