# -*- coding: utf-8 -*-
"""task1_a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g20hEOUSDwR0RgiyJVODBXLOPROVrIHu
"""

inp_file=open('input1_a.txt',"r")
out_file=open('output1_a.txt',"w")


empty_lst=[]
str_1=""
read_line= inp_file.readline()
t_line= inp_file.readlines()

temp=t_line[0]
lst_1=temp.split()


for a in lst_1:
  empty_lst.append(int(a) )

def quick_s(arr,first,last) :
  if first< last :
    store= partition_f(arr,first,last)
    quick_s (arr,first,store-1)
    quick_s (arr,store+1,last)
  return arr
#----------------------
def partition_f(arr,first,last):
  save=arr[last]
  x=first-1
    
  for b in range(first,last):
    
    if arr[b]<save:
      x=x+1
      arr[x],arr[b]= arr[b],arr[x]
    
  arr[x+1],arr[last]=arr[last],arr[x+1]
  final_value=x+1
  return final_value

final_value=quick_s(empty_lst,0,len(empty_lst)-1)


for c in final_value:
  str_1=str_1+str(c)+" "
#------------------------------------------    
out_file.write(str_1)
inp_file.close()
out_file.close()

